const paragraphs=[
    "Regular physical exercise is necessary to keep good health. Walking in the open air every morning and evening strengthens the muscles of the limbs and quickens the circulation of blood. A game every day before sunset is very advantageous. A man, taking regular exercise, will be much better fitted for the duties of life than a languid bookworm will. The first requisite is pure air. To secure good health we must have a sufficient supply of fresh air. For this we should keep the environment clean.",
    "Failures can crush the positivity in a person. The initial excitement of doing something new can give way to dejection and disappointment if success is not achieved quickly. The motivation levels can dip significantly. It is in this scenario that the character of a person is known. A person who keeps working hard and doesn't let his/her motivational levels dip is more likely to emerge as a winner than a person who doesn't believe in what he/she does and therefore lose interest.",
    "Patriotism is a feeling that fills a person’s heart with pride when he/she thinks of the nation; it's a feeling which results from a sense of belongingness to one's country. It binds people from diverse communities, religions and races together and gives them a sense of belonging, a sense of being rooted. The feeling is most strongly visible in the soldiers who sacrifice their lives for their countries. Though the common man might never get an opportunity to make such sacrifices for the country, the feeling of patriotism lingers in his heart forever, making him pledge his devotion to his/her country.",
    "We depend on food for our living. With the introduction of methods and techniques of cultivation, human-beings are able to increase food output. The modern irrigation technologies has helped to cultivate lands that were otherwise considered barren. The agriculture equipment such as tractor helps the farmer in his farming. Increased industrial output: As a result of introduction of technology in the process of producing goods, there has been tremendous increase in the industrial output. The automation of industries processes has resulted in processing tasks effectively and efficiently. Large industries make good use of engineering technology for large scale production of goods.",
    "Patriotism for the country, in this case, translates into patriotism for that person. However, patriotism assumes a different connotation in a democracy, where the people of the country elect their government and where the government is accountable to the people. Love for the country, in this case, might not converge with love for the government. The value of patriotism demands that the citizens love their country, remain loyal and committed to the development of the country. It is a feeling that should reside in the hearts of all the citizens of a country at all times. Whether this feeling of love, loyalty and commitment towards one's country reflect on the government, depends on its functioning and the credibility that the government enjoys among the citizens.",
    "In this fast-paced world, time is money and everything needs to be done in the shortest time possible. You see that several job postings include a minimum typing speed in terms of words per minute in their list of requirements. With the widespread use of computers, almost everyone knows how to type. The real question is how fast you can type, which is measured by taking a standard wpm test. It is not only the typing speed; accuracy also matters. This is measured in terms of percentage and most employers expect 90% or more.",
    "Education and empowerment go hand in hand. If we are to empower girls, it is imperative to give women access to education. It is no coincidence that an improvement in the condition of women has coincided with an increase in the literacy rates of women to more than 50 per cent today. It is also important, at the same time, to sensitise the men of the society on gender issues so that the existing gender bias can be wiped off.",
    "Cleanliness is necessary for good health. It is the most important hygiene habit. Dirt spreads diseases, because germs thrive in it. They move about with the dust in the air, so a dirty man is easily attacked with diseases. The man, who has a clean body and puts on clean clothes, is free from dirt and dust, and no disease can attack him easily. Daily bathing is a good habit. It keeps our body clean. We should keep our clothes, beddings, food, utensils, and all other things neat and clean. No dirt should be allowed to gather near our houses. We should also keep our teeth and nails clean. We should remember that cleanliness is next to godliness.",
    "We believe that an empowered woman can change a lot in the society. Unlike other Women Empowerment programs, we believe that Money as an energy is one of the most powerful empowerment tools. We believe in practical steps to create income for women, who are capable and intelligent and willing to work, however due to various reasons are unable to do it today. The reasons could be varied for various women, some women could be deprived of these opportunities because their men don't want them to work, the others may be restricted due to family pressures or peer pressures."
];